/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   redirect.c                                         :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: leoaguia <leoaguia@student.42.fr>          +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2025/12/25 21:50:11 by leoaguia          #+#    #+#             */
/*   Updated: 2026/01/12 19:03:03 by leoaguia         ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#include "minishell.h"

/*
Checks if the file is a temporary heredoc generated by minishell.
If so, deletes it from disk (unlink) to avoid leaving garbage, but keeps the FD open.
*/
static void	unlink_if_heredoc(t_redir *r)
{
	if (r->type == R_IN && !access(r->target, F_OK))
	{
		if (ft_strncmp(r->target, ".heredoc_", 9) == 0)
			unlink(r->target);
	}
}

/*
Opens normal input/output files.
Includes automatic cleanup of temporary files (.heredoc_*).
*/
static int	open_file(t_redir *r)
{
	int	fd;

	fd = -1;
	if (r->type == R_IN)
		fd = open(r->target, O_RDONLY);
	else if (r->type == R_OUT)
		fd = open(r->target, O_WRONLY | O_CREAT | O_TRUNC, 0644);
	else if (r->type == R_APP)
		fd = open(r->target, O_WRONLY | O_CREAT | O_APPEND, 0644);
	if (fd == -1)
	{
		ft_putstr_fd("minishell: ", 2);
		perror(r->target);
	}
	else
		unlink_if_heredoc(r);
	return (fd);
}

/*
Applies dup2 for STDIN or STDOUT and closes the original fd.
*/
static void	apply_dup(int fd, int type)
{
	if (type == R_IN || type == R_HDC)
		dup2(fd, STDIN_FILENO);
	else if (type == R_OUT || type == R_APP)
		dup2(fd, STDOUT_FILENO);
	close(fd);
}

/*
Iterates over the redirections list and applies them.
*/
int	setup_redirects(t_cmd *cmd)
{
	t_redir	*tmp;
	int		fd;

	tmp = cmd->redirs;
	while (tmp)
	{
		fd = open_file(tmp);
		if (fd == -1)
			return (1);
		apply_dup(fd, tmp->type);
		tmp = tmp->next;
	}
	return (0);
}
